pkp_api:
    resource: "@PKPApiBundle/Controller/"
    type:     annotation
    prefix:   /

pkp_lan_party:
    resource: "@PKPLanPartyBundle/Controller/"
    type:     annotation
    prefix:   /

pkp_admin:
    resource: "@PKPAdminBundle/Controller/"
    type:     annotation
    prefix:   /

pkp_admin_routing:
    resource: "@PKPAdminBundle/Resources/config/admin_routing.yml"

pkp_auth:
    resource: "@PKPAuthBundle/Controller/"
    type:     annotation
    prefix:   /

pkp_auth_user_routing:
    resource: "@PKPAuthBundle/Resources/config/routing.yml"

pkp_web:
    resource: "@PKPWebBundle/Controller/"
    type:     annotation
    prefix:   /


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc