pkp_api:
    resource: "@PKPApiBundle/Resources/config/routing.yml"
    prefix:   /api

pkp_lan_party:
    resource: "@PKPLanPartyBundle/Controller/"
    type:     annotation
    prefix:   /

pkp_admin:
    resource: "@PKPAdminBundle/Controller/"
    type:     annotation
    prefix:   /

pkp_admin_routing:
    resource: "@PKPAdminBundle/Resources/config/admin_routing.yml"

pkp_auth:
    resource: "@PKPAuthBundle/Controller/"
    type:     annotation
    prefix:   /

pkp_auth_user_routing:
    resource: "@PKPAuthBundle/Resources/config/routing.yml"

pkp_web:
    resource: "@PKPWebBundle/Controller/"
    type:     annotation
    prefix:   /


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc


gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media